export const REGISTRATION_FIELDS = {
    ID: 'id',
    /* Basic Information */
    FIRST_NAME: 'FIRST_NAME',
    LAST_NAME: 'LAST_NAME',
    EMAIL: 'EMAIL',
    GENDER: 'GENDER',
    /* School */
    ACADEMIC_YEAR: 'ACADEMIC_YEAR',
    MAJOR: 'MAJOR',
    SCHOOL: 'SCHOOL',
    /* Logistics */
    TRANSPORTATION: 'TRANSPORTATION',
    SHIRT_SIZE: 'SHIRT_SIZE',
    DIETARY_RESTRICTIONS: 'DIETARY_RESTRICTIONS',
    /* Interests */
    JOB_INTERESTS: 'JOB_INTERESTS',
    PROFESSIONAL_INTERESTS: 'PROFESSIONAL_INTERESTS',
    /* Feedback */
    LEAD_SOURCE: 'LEAD_SOURCE'
  };
  
  export default {
    REGISTRATION_FIELDS
  };